const project = { ref: 'projects' }

export const schema = {
  projects: {
    name: 'text',
    description: 'text',
    status: 'text',
    goal: 'text',
    deadline: 'text',
    progress: 'int',
    color: 'text',
    icon: 'text',
    area: 'text',
    pinned: 'bool',
  },
  goals: {
    title: 'text',
    description: 'text',
    project_id: project,
    target_value: 'real',
    current_value: 'real',
    unit: 'text',
    deadline: 'text',
    status: 'text',
    metric: 'text',
  },
  partners: {
    name: 'text',
    company: 'text',
    phone: 'text',
    email: 'text',
    telegram: 'text',
    city: 'text',
    source: 'text',
    status: 'text',
    comment: 'text',
    next_action: 'text',
    next_action_date: 'text',
    project_id: project,
  },
  partner_reports: {
    partner_id: { ref: 'partners', onDelete: 'cascade' },
    date: 'text',
    applications: 'int',
    approvals: 'int',
    turnover: 'money',
    profit: 'money',
    note: 'text',
  },
  tasks: {
    title: 'text',
    description: 'text',
    due_date: 'text',
    due_time: 'text',
    priority: 'text',
    status: 'text',
    project_id: project,
    partner_id: { ref: 'partners' },
    goal_id: { ref: 'goals' },
    completed_at: 'text',
    repeat: 'text',
    repeat_days: 'json',
    repeat_interval: 'int',
    repeat_spawned: 'bool',
    reminded_at: 'text',
  },
  events: {
    title: 'text',
    description: 'text',
    start: 'text',
    end: 'text',
    all_day: 'bool',
    color: 'text',
    project_id: project,
    partner_id: { ref: 'partners' },
  },
  habits: {
    name: 'text',
    description: 'text',
    kind: 'text',
    frequency: 'text',
    days: 'json',
    per_week: 'int',
    color: 'text',
    project_id: project,
    start_date: 'text',
    archived: 'bool',
  },
  habit_logs: {
    habit_id: { ref: 'habits', onDelete: 'cascade' },
    date: 'text',
    status: 'text',
  },
  partner_interactions: {
    partner_id: { ref: 'partners', onDelete: 'cascade' },
    date: 'text',
    type: 'text',
    note: 'text',
  },
  trades: {
    date: 'text',
    instrument: 'text',
    direction: 'text',
    entry: 'decimal',
    exit: 'decimal',
    stop_loss: 'decimal',
    take_profit: 'decimal',
    size: 'decimal',
    risk: 'money',
    pnl: 'money',
    fees: 'money',
    strategy: 'text',
    setup_reason: 'text',
    comment: 'text',
    mistakes: 'text',
    conclusions: 'text',
    screenshot: 'text',
    project_id: project,
  },
  trading_topics: {
    title: 'text',
    category: 'text',
    status: 'text',
    notes: 'text',
    project_id: project,
  },
  products: {
    name: 'text',
    brand: 'text',
    volume: 'text',
    purchase_price: 'money',
    sale_price: 'money',
    stock: 'int',
    project_id: project,
  },
  customers: {
    name: 'text',
    phone: 'text',
    instagram: 'text',
    city: 'text',
    notes: 'text',
  },
  sales: {
    date: 'text',
    product_id: { ref: 'products' },
    customer_id: { ref: 'customers' },
    quantity: 'int',
    amount: 'money',
    cost: 'money',
    payment_method: 'text',
    note: 'text',
    project_id: project,
  },
  biz_expenses: {
    date: 'text',
    category: 'text',
    amount: 'money',
    note: 'text',
    project_id: project,
  },
  content: {
    title: 'text',
    idea: 'text',
    script: 'text',
    platform: 'text',
    status: 'text',
    publish_date: 'text',
    url: 'text',
    project_id: project,
  },
  accounts: {
    name: 'text',
    kind: 'text',
    initial_balance: 'money',
    color: 'text',
    archived: 'bool',
  },
  transactions: {
    date: 'text',
    kind: 'text',
    amount: 'money',
    account_id: { ref: 'accounts', onDelete: 'cascade' },
    to_account_id: { ref: 'accounts', onDelete: 'cascade' },
    category: 'text',
    note: 'text',
    project_id: project,
  },
  budgets: {
    category: 'text',
    amount: 'money',
  },
  reviews: {
    week_start: 'text',
    wins: 'text',
    problems: 'text',
    lessons: 'text',
    focus: 'text',
    rating: 'int',
  },
}

export const isRef = (type) => typeof type === 'object' && type !== null

export const tableOrder = Object.keys(schema)

export const internalColumns = ['repeat_spawned', 'reminded_at']

export const dateColumn = {
  tasks: 'due_date',
  events: 'start',
  habit_logs: 'date',
  partner_interactions: 'date',
  partner_reports: 'date',
  trades: 'date',
  sales: 'date',
  biz_expenses: 'date',
  transactions: 'date',
  reviews: 'week_start',
}

export const sqlType = {
  text: 'text',
  int: 'integer',
  real: 'double precision',
  money: 'numeric(18,2)',
  decimal: 'numeric(24,8)',
  bool: 'boolean',
  json: 'jsonb',
}
