import { expect, test } from '@playwright/test'
import { codeAt, currentStep } from '../server/src/lib/totp.ts'

test('admin workspace: loading, diagnostics, users, errors and audit', async ({ page }) => {
  test.setTimeout(90_000)
  const setup = await page.request.post('/api/admin/auth/login', { data: { login: 'admin-e2e', password: 'admin-password' } }).then((r) => r.json())
  expect(setup.setupRequired).toBe(true)
  const login = await page.request.post('/api/admin/auth/login/2fa', { data: { ticket: setup.ticket, code: codeAt(setup.secret, currentStep()) } })
  expect(login.ok()).toBe(true)
  const nav = page.getByRole('navigation', { name: 'Разделы админки' })
  await test.step('a slow overview shows a skeleton and then meaningful diagnostics', async () => {
    await page.route('**/api/admin/overview', async (route) => {
      await new Promise((resolve) => setTimeout(resolve, 700))
      await route.continue()
    })
    await page.goto('/admin/')
    await expect(page.getByRole('status', { name: 'Загрузка данных' }).first()).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Обзор', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Доставка уведомлений' })).toBeVisible()
    await expect(page.getByRole('status', { name: 'Загрузка данных' })).toHaveCount(0)
    await page.screenshot({ path: '/tmp/dahar-admin-overview.png', fullPage: true })
    await page.unroute('**/api/admin/overview')
  })
  await test.step('users can be searched, opened, updated and exported', async () => {
    for (let i = 0; i < 51; i++) {
      const created = await page.request.post('/api/admin/users', {
        data: { login: `pagination-${i}`, password: 'pagination-password', name: i === 50 ? '=SUM(A1:A2)' : `Pagination ${i}` },
      })
      expect(created.status()).toBe(201)
    }
    await nav.getByRole('link', { name: 'Пользователи', exact: true }).click()
    await page.getByRole('textbox', { name: 'Поиск пользователей' }).fill('pagination-')
    await expect(page.locator('tbody tr')).toHaveCount(50)
    const csvDownload = page.waitForEvent('download')
    await page.getByRole('button', { name: 'CSV страницы' }).click()
    const stream = await (await csvDownload).createReadStream()
    const chunks: Buffer[] = []
    for await (const chunk of stream!) chunks.push(chunk)
    expect(Buffer.concat(chunks).toString()).toContain('"\'=SUM(A1:A2)"')
    await page.getByRole('button', { name: 'Далее', exact: true }).click()
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await expect(page).toHaveURL(/offset=50/)
    await page.getByRole('textbox', { name: 'Поиск пользователей' }).fill('e2e-onboarding')
    await expect(page.getByRole('link', { name: /@e2e-onboarding/ })).toBeVisible()
    await expect(page.locator('tbody tr')).toHaveCount(1)
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: 'CSV страницы' }).click()
    expect((await download).suggestedFilename()).toBe('dahar-users-page.csv')
    await page.getByRole('link', { name: /@e2e-onboarding/ }).click()
    await expect(page.getByRole('heading', { name: 'Первые полезные действия' })).toBeVisible()
    await expect(page.getByText('Защита 2FA', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Переименовать' }).click()
    const modal = page.getByRole('dialog', { name: 'Имя пользователя' })
    await modal.getByLabel('Имя', { exact: true }).fill('Админ изменил имя')
    await modal.getByRole('button', { name: 'Сохранить' }).click()
    await expect(modal).toBeHidden()
    await expect(page.getByRole('heading', { name: 'Админ изменил имя', exact: true })).toBeVisible()
    await nav.getByRole('link', { name: 'Пользователи', exact: true }).click()
    await page.evaluate(() =>
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('Unavailable')) } }),
    )
    await page.getByRole('button', { name: 'Пользователь', exact: true }).click()
    const create = page.getByRole('dialog', { name: 'Новый пользователь' })
    await create.getByLabel(/^Логин/).fill('gui-user')
    await create.getByRole('button', { name: 'Создать', exact: true }).click()
    const credentials = page.getByRole('dialog', { name: 'Пользователь создан' })
    await expect(credentials).toBeVisible()
    await expect(credentials.getByLabel(/^Пароль/)).toHaveAttribute('readonly', '')
    await expect(credentials.getByRole('button', { name: 'Создать', exact: true })).toBeHidden()
    await credentials.getByRole('button', { name: 'Готово', exact: true }).click()
  })
  await test.step('subscriptions, payment journal, Telegram and AI are visible', async () => {
    await nav.getByRole('link', { name: 'Подписки', exact: true }).click()
    await page.getByRole('textbox', { name: 'Поиск по пользователю' }).fill('gui-user')
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await expect(page.locator('tbody')).toContainText('Пробный период')
    await expect(page.getByText('Приём платежей ещё не подключён.', { exact: false })).toBeVisible()
    await page.getByRole('link', { name: '0 оплаченных →', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Платежи', exact: true })).toBeVisible()
    await expect(page.getByText('Платежей ещё нет', { exact: true })).toBeVisible()
    await nav.getByRole('link', { name: 'Telegram', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Telegram', exact: true })).toBeVisible()
    await page.getByRole('combobox', { name: 'Подключения Telegram' }).selectOption('miniapp')
    await expect(page.getByText('Записей пока нет', { exact: true })).toBeVisible()
    await nav.getByRole('link', { name: 'Доставки', exact: true }).click()
    await page.getByRole('combobox', { name: 'Статус доставки' }).selectOption('failed')
    await expect(page.getByRole('heading', { name: 'Доставки', exact: true })).toBeVisible()
    await nav.getByRole('link', { name: 'AI и расходы', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'AI и расходы', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Статус AI' })).toBeVisible()
    await page.screenshot({ path: '/private/tmp/dahar-admin-ai-new.png', fullPage: true })
  })
  await test.step('a failing query offers retry and a failed refresh keeps existing data', async () => {
    await page.route('**/api/admin/errors?**', (route) => route.fulfill({ status: 400, json: { error: 'Тестовая ошибка загрузки' } }))
    await nav.getByRole('link', { name: 'Ошибки', exact: true }).click()
    await expect(page.getByText('Не удалось загрузить данные', { exact: true })).toBeVisible()
    await expect(page.getByText('Ошибок по фильтру нет')).toBeHidden()
    await page.unroute('**/api/admin/errors?**')
    await page.getByRole('button', { name: 'Повторить' }).click()
    await expect(page.getByRole('heading', { name: 'Ошибок в день' })).toBeVisible()
    await page.route('**/api/admin/errors?**', (route) => route.fulfill({ status: 400, json: { error: 'Обновление временно недоступно' } }))
    await page.getByRole('button', { name: 'Обновить', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Показаны последние загруженные данные')
    await expect(page.getByRole('heading', { name: 'Ошибок в день' })).toBeVisible()
    await page.unroute('**/api/admin/errors?**')
    await page.getByRole('button', { name: 'Очистить журнал' }).click()
    await expect(page.getByRole('dialog', { name: 'Очистить весь журнал ошибок?' })).toBeVisible()
    await page.getByRole('button', { name: 'Отмена', exact: true }).click()
  })
  await test.step('audit filters and system diagnostics are available', async () => {
    await nav.getByRole('link', { name: 'Журнал действий' }).click()
    await page.getByRole('combobox', { name: 'Тип действия' }).selectOption('user_rename')
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await page.getByRole('button', { name: 'Детали', exact: true }).click()
    await expect(page.locator('pre')).toContainText('Админ изменил имя')
    await nav.getByRole('link', { name: 'Система', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Соединения и статистика PostgreSQL' })).toBeVisible()
    await expect(page.getByRole('columnheader', { name: 'Мёртвых строк ≈' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Найти таблицу' }).fill('notification_deliveries')
    await expect(page.locator('tbody tr')).toHaveCount(1)
    await page.getByRole('textbox', { name: 'Найти таблицу' }).fill('')
    await page.getByRole('button', { name: 'Тёмная тема', exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await page.screenshot({ path: '/tmp/dahar-admin-dark.png', fullPage: true })
    await page.getByRole('button', { name: 'Светлая тема', exact: true }).click()
    await page.screenshot({ path: '/tmp/dahar-admin-system.png', fullPage: true })
    await page.setViewportSize({ width: 393, height: 852 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(page.getByRole('button', { name: 'Выйти', exact: true })).toBeVisible()
  })
})
