import { expect, test } from '@playwright/test'
import { unique, USER } from './helpers'

test('task checklist changes persist after reload', async ({ page, context }) => {
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-b', password: USER.password } })
  const title = unique('Checklist task')
  await context.request.post('/api/tasks', {
    data: { title, status: 'todo', checklist: '- [ ] Проверить условия\n- [ ] Отправить письмо', estimate_minutes: 30 },
  })
  await page.goto('/tasks')
  const row = page.locator('div.group').filter({ has: page.getByRole('button', { name: title, exact: true }) })
  await row.locator('summary').click()
  const checkbox = row.getByRole('checkbox', { name: 'Проверить условия', exact: true })
  await checkbox.click()
  await expect(checkbox).toBeChecked()
  await expect(row.locator('summary')).toHaveText('Шаги: 1/2')
  await page.reload()
  await row.locator('summary').click()
  await expect(checkbox).toBeChecked()
  await expect(row.getByRole('checkbox', { name: 'Отправить письмо', exact: true })).not.toBeChecked()
})

test('a restored cache is never displayed under a different account', async ({ page, context }) => {
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-a', password: USER.password } })
  const title = unique('Private task A')
  await context.request.post('/api/tasks', { data: { title, status: 'todo' } })
  await page.goto('/tasks')
  await expect(page.getByRole('button', { name: title, exact: true })).toBeVisible()
  await page.waitForTimeout(2500)
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-b', password: USER.password } })
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Задачи', exact: true })).toBeVisible()
  await expect(page.getByText(title, { exact: true })).toHaveCount(0)
  const current = await context.request.get('/api/auth/me').then((response) => response.json())
  expect(current.user.login).toBe('e2e-launch-b')
})
test('collection failure offers retry instead of an empty list', async ({ page, context }) => {
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-a', password: USER.password } })
  await page.route('**/api/tasks?**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":"Temporarily unavailable"}' }))
  await page.goto('/tasks')
  await expect(page.getByRole('alert').filter({ hasText: 'Не удалось загрузить данные' })).toBeVisible({ timeout: 15000 })
  await expect(page.getByText('Ничего не найдено', { exact: true })).toBeHidden()
  await page.unroute('**/api/tasks?**')
  await page.getByRole('button', { name: 'Повторить загрузку', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Задачи', exact: true })).toBeVisible()
  await expect(page.getByRole('alert').filter({ hasText: 'Не удалось загрузить данные' })).toBeHidden()
})
test('review draft survives refetch and moving between weeks', async ({ page, context }) => {
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-a', password: USER.password } })
  await page.goto('/review')
  const field = page.getByRole('textbox', { name: 'Что получилось', exact: true })
  await field.fill('My unsaved weekly draft')
  const review = await context.request.get('/api/reviews').then((response) => response.json())
  if (review.length) await context.request.patch(`/api/reviews/${review[0].id}`, { data: { wins: 'New server text' } })
  await page.goto('/tasks')
  await page.goto('/review')
  await expect(field).toHaveValue('My unsaved weekly draft')
  await page.reload()
  await expect(field).toHaveValue('My unsaved weekly draft')
})
test('admin navigation cannot replace the offline client shell', async ({ page, context }) => {
  await context.request.post('/api/auth/login', { data: { login: 'e2e-launch-a', password: USER.password } })
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Задачи', exact: true })).toBeVisible()
  await page.waitForFunction(() => !!navigator.serviceWorker.controller)
  await page.waitForTimeout(2500)
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name: 'Вход для владельца', exact: true })).toBeVisible()
  await context.setOffline(true)
  await page.goto('/tasks')
  await expect(page.getByRole('heading', { name: 'Задачи', exact: true })).toBeVisible()
})
